# Database
mysql:
  enabled: false
  host: 'localhost'
  port: 3306
  database: 'database'
  username: 'username'
  password: 'password'

# Language File
language: 'de-de'

# Game Information
countdown:
  minPlayers: 2
  startValue: 10
