# Database
mysql:
  enabled: false
  host: 'localhost'
  port: 3306
  database: 'database'
  username: 'username'
  password: 'password'

# Language File
language: 'de-de'

# Game Information
countdown:
  minPlayers: 2
  startValue: 10

lobby:
  world: world
  pos1:
    x: 10
    y: 10
    z: 10
  pos2:
    x: -10
    y: 80
    z: -10
  spawn:
    x: 0
    y: 52
    z: 0
    yaw: 0
    pitch: 0
# Spawner speeds
spawner:
  bronze:
    level1: 2
    level2: 1.5
    level3: 1
  iron:
    level1: 5
    level2: 4
    level3: 3
  gold:
    level1: 30
    level2: 25
    level3: 20
